waypoint:
  .byte NORTH_BITMASK, NORTH_BITMASK, NORTH_BITMASK, NORTH_BITMASK, NORTH_BITMASK, NORTH_BITMASK, NORTH_BITMASK, NORTH_BITMASK
  .byte EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK
  .byte SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK
  .byte WEST_BITMASK, WEST_BITMASK, WEST_BITMASK, WEST_BITMASK, WEST_BITMASK, WEST_BITMASK, WEST_BITMASK, WEST_BITMASK
  .byte EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK, EAST_BITMASK
  .byte SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK
  .byte SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK, SOUTH_BITMASK
  .byte NORTH_EAST_BITMASK, NORTH_EAST_BITMASK, NORTH_EAST_BITMASK, NORTH_EAST_BITMASK, NORTH_EAST_BITMASK, NORTH_EAST_BITMASK, NORTH_EAST_BITMASK, NORTH_EAST_BITMASK
  .byte SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK, SOUTH_EAST_BITMASK

.proc NPCInit
  jsr _resetWayPoint
  rts
.endproc

.proc _resetWayPoint
  lda #$40  ; This should be the number of bytes in `waypoint`.
  sta way_point_ptr
  rts
.endproc

.proc RenderNPCDirectionSprite
  ldx way_point_ptr
  lda waypoint, X
  ;and #%00001111
  sta param_1
  lda #$04
  sta param_2
  lda #%00000001
  sta param_3
  jsr RenderBirdSprite
END_SELECT_SPRITE:
  rts
.endproc

.proc NPCMoveNorth
  dec $0204
  rts
.endproc

.proc NPCMoveEast
  inc $0207
  rts
.endproc

.proc NPCMoveSouth
  inc $0204
  rts
.endproc

.proc NPCMoveWest
  dec $0207
  rts
.endproc

.proc NPCMove
  dec way_point_ptr
  bne SKIP_RESET
RESET:
  jsr _resetWayPoint
SKIP_RESET:
  ldx way_point_ptr
  lda waypoint, X
NORTH:
  cmp #NORTH_BITMASK
  bne EAST
  jsr NPCMoveNorth
EAST:
  cmp #EAST_BITMASK
  bne SOUTH
  jsr NPCMoveEast
SOUTH:
  cmp #SOUTH_BITMASK
  bne WEST
  jsr NPCMoveSouth
WEST:
  cmp #WEST_BITMASK
  bne NORTH_EAST
  jsr NPCMoveWest
NORTH_EAST:
  cmp #NORTH_EAST_BITMASK
  bne EXIT
  jsr NPCMoveNorth
  jsr NPCMoveEast
SOUTH_EAST:
  cmp #SOUTH_EAST_BITMASK
  bne EXIT
  jsr NPCMoveSouth
  jsr NPCMoveEast
EXIT:
  rts
.endproc

